// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// IOAdapter is an autogenerated mock type for the IOAdapter type
type IOAdapter struct {
	mock.Mock
}

// Output provides a mock function with given fields: content
func (_m *IOAdapter) Output(content string) error {
	ret := _m.Called(content)

	if len(ret) == 0 {
		panic("no return value specified for Output")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(content)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIOAdapter creates a new instance of IOAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIOAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *IOAdapter {
	mock := &IOAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
