// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"

	domain "github.com/central-university-dev/backend_academy_2024_project_3-go-Matthew11K/internal/domain"
)

// LogParser is an autogenerated mock type for the LogParser type
type LogParser struct {
	mock.Mock
}

// Parse provides a mock function with given fields: line
func (_m *LogParser) Parse(line string) (*domain.LogRecord, error) {
	ret := _m.Called(line)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 *domain.LogRecord
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*domain.LogRecord, error)); ok {
		return rf(line)
	}
	if rf, ok := ret.Get(0).(func(string) *domain.LogRecord); ok {
		r0 = rf(line)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.LogRecord)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(line)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewLogParser creates a new instance of LogParser. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLogParser(t interface {
	mock.TestingT
	Cleanup(func())
}) *LogParser {
	mock := &LogParser{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
